# Copyright (c) 2023, Alliance for Open Media. All rights reserved
#
# This source code is subject to the terms of the BSD 3-Clause Clear License
# and the Alliance for Open Media Patent License 1.0. If the BSD 3-Clause Clear
# License was not distributed with this source code in the LICENSE file, you
# can obtain it at www.aomedia.org/license/software-license/bsd-3-c-c. If the
# Alliance for Open Media Patent License 1.0 was not distributed with this
# source code in the PATENTS file, you can obtain it at
# www.aomedia.org/license/patent.

# proto-file: iamf/cli/proto/user_metadata.proto
# proto-message: UserMetadata

test_vector_metadata {
  human_readable_description:
    "A third-order ambisonics IAMF stream encoded using "
    "`ambisonics_mode` = `MONO`."
  file_name_prefix: "test_000039"
  is_valid: true
  is_valid_to_decode: true
  validate_user_loudness: true
  mp4_fixed_timestamp: "2023-05-12 00:00:00"
  test_repository_tags: [
    "github/aomediacodec/libiamf/main",
    "github/aomediacodec/libiamf/v1.0.0-errata"
  ]
  primary_tested_spec_sections: [
    "3.6.3/ambisonics_mono_config",
    "7/IAMF Processing",
    "7.1/channel_mapping",
    "7.3.2/Rendering an Audio Element",
    "7.3.2.2/Rendering a Scene-Based Audio Element to Loudspeakers"
  ]
  base_test: "test_000038"
}

encoder_control_metadata {
  add_build_information_tag: false
  output_rendered_file_format: OUTPUT_FORMAT_WAV_BIT_DEPTH_AUTOMATIC
}

ia_sequence_header_metadata {
  primary_profile: PROFILE_VERSION_SIMPLE
  additional_profile: PROFILE_VERSION_SIMPLE
}

codec_config_metadata {
  codec_config_id: 200
  codec_config {
    codec_id: CODEC_ID_LPCM
    num_samples_per_frame: 64
    audio_roll_distance: 0
    decoder_config_lpcm {
      sample_format_flags: LPCM_LITTLE_ENDIAN
      sample_size: 16
      sample_rate: 48000
    }
  }
}

audio_element_metadata {
  audio_element_id: 300
  audio_element_type: AUDIO_ELEMENT_SCENE_BASED
  reserved: 0
  codec_config_id: 200
  audio_substream_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  ambisonics_config {
    ambisonics_mode: AMBISONICS_MODE_MONO
    ambisonics_mono_config {
      output_channel_count: 16
      substream_count: 16
      channel_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    }
  }
}

mix_presentation_metadata {
  mix_presentation_id: 42
  annotations_language: ["en-us"]
  localized_presentation_annotations: ["test_mix_pres"]
  sub_mixes {
    audio_elements {
      audio_element_id: 300
      localized_element_annotations: ["test_sub_mix_0_audio_element_0"]
      rendering_config {
        headphones_rendering_mode: HEADPHONES_RENDERING_MODE_STEREO
      }
      element_mix_gain {
        param_definition {
          parameter_id: 100
          parameter_rate: 48000
          param_definition_mode: 1
          reserved: 0
        }
        default_mix_gain: 0
      }
    }
    output_mix_gain {
      param_definition {
        parameter_id: 100
        parameter_rate: 48000
        param_definition_mode: 1
        reserved: 0
      }
      default_mix_gain: 0
    }
    layouts {
      loudness_layout {
        layout_type: LAYOUT_TYPE_LOUDSPEAKERS_SS_CONVENTION
        ss_layout {
          sound_system: SOUND_SYSTEM_A_0_2_0
          reserved: 0
        }
      }
      loudness {
        info_type_bit_masks: []
        integrated_loudness: -5807
        digital_peak: -4704
      }
    }
  }
}

audio_frame_metadata {
  wav_filename: "sawtooth_8000_toa_48khz.wav"
  samples_to_trim_at_end: 0
  samples_to_trim_at_start: 0
  audio_element_id: 300
  channel_metadatas: [
    { channel_id: 0 channel_label: CHANNEL_LABEL_A_0 },
    { channel_id: 1 channel_label: CHANNEL_LABEL_A_1 },
    { channel_id: 2 channel_label: CHANNEL_LABEL_A_2 },
    { channel_id: 3 channel_label: CHANNEL_LABEL_A_3 },
    { channel_id: 4 channel_label: CHANNEL_LABEL_A_4 },
    { channel_id: 5 channel_label: CHANNEL_LABEL_A_5 },
    { channel_id: 6 channel_label: CHANNEL_LABEL_A_6 },
    { channel_id: 7 channel_label: CHANNEL_LABEL_A_7 },
    { channel_id: 8 channel_label: CHANNEL_LABEL_A_8 },
    { channel_id: 9 channel_label: CHANNEL_LABEL_A_9 },
    { channel_id: 10 channel_label: CHANNEL_LABEL_A_10 },
    { channel_id: 11 channel_label: CHANNEL_LABEL_A_11 },
    { channel_id: 12 channel_label: CHANNEL_LABEL_A_12 },
    { channel_id: 13 channel_label: CHANNEL_LABEL_A_13 },
    { channel_id: 14 channel_label: CHANNEL_LABEL_A_14 },
    { channel_id: 15 channel_label: CHANNEL_LABEL_A_15 }
  ]
}

parameter_block_metadata {
  parameter_id: 100
  start_timestamp: 0
  duration: 24000
  constant_subblock_duration: 24000
  subblocks: [
    {
      mix_gain_parameter_data {
        animation_type: ANIMATE_STEP
        param_data {
          step {
            start_point_value: 0
          }
        }
      }
    }
  ]
}

temporal_delimiter_metadata {
  enable_temporal_delimiters: false
}
