# Copyright (c) 2024, Alliance for Open Media. All rights reserved
#
# This source code is subject to the terms of the BSD 3-Clause Clear License
# and the Alliance for Open Media Patent License 1.0. If the BSD 3-Clause Clear
# License was not distributed with this source code in the LICENSE file, you
# can obtain it at www.aomedia.org/license/software-license/bsd-3-c-c. If the
# Alliance for Open Media Patent License 1.0 was not distributed with this
# source code in the PATENTS file, you can obtain it at
# www.aomedia.org/license/patent.

# proto-file: third_party/iamf_tools/iamf/cli/proto/user_metadata.proto
# proto-message: UserMetadata

test_vector_metadata {
  human_readable_description:
    "A simple example of a fourth-order mono ambisonics + 3.0Ch "
    "Base-Enhanced profile IAMF stream and a Mono output layout."
  file_name_prefix: "test_000614"
  is_valid: true
  is_valid_to_decode: true
  validate_user_loudness: true
  mp4_fixed_timestamp: "2024-08-08 00:00:00"
  test_repository_tags: ["github/aomediacodec/libiamf/main"]
  primary_tested_spec_sections: [
    "3.6.2/loudspeaker_layout == Expanded",
    "3.6.2/expanded_loudspeaker_layout == 3.0ch",
    "3.6.3/ambisonics_mono_config",
    "3.7.3/sound_system == Mono",
    "3.7.4/default_mix_gain",
    "4.2/Base-Enhanced Profile",
    "8.5.1/Loudness Information"
  ]
  base_test: "test_000400"
}

ia_sequence_header_metadata {
  primary_profile: PROFILE_VERSION_BASE_ENHANCED
  additional_profile: PROFILE_VERSION_BASE_ENHANCED
}

codec_config_metadata {
  codec_config_id: 200
  codec_config {
    codec_id: CODEC_ID_LPCM
    num_samples_per_frame: 1024
    audio_roll_distance: 0
    decoder_config_lpcm {
      sample_format_flags: LPCM_LITTLE_ENDIAN
      sample_size: 16
      sample_rate: 48000
    }
  }
}

audio_element_metadata: [
  {
    audio_element_id: 300
    audio_element_type: AUDIO_ELEMENT_SCENE_BASED
    reserved: 0
    codec_config_id: 200
    num_substreams: 25
    audio_substream_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
    num_parameters: 0
    ambisonics_config {
      ambisonics_mode: AMBISONICS_MODE_MONO
      ambisonics_mono_config {
        output_channel_count: 25
        substream_count: 25
        channel_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
      }
    }
  },
  {
    audio_element_id: 301
    audio_element_type: AUDIO_ELEMENT_CHANNEL_BASED
    reserved: 0
    codec_config_id: 200
    num_substreams: 2
    audio_substream_ids: [25, 26]
    num_parameters: 0
    scalable_channel_layout_config {
      num_layers: 1
      reserved: 0
      channel_audio_layer_configs: [
        {
          loudspeaker_layout: LOUDSPEAKER_LAYOUT_EXPANDED
          output_gain_is_present_flag: 0
          recon_gain_is_present_flag: 0
          reserved_a: 0
          substream_count: 2
          coupled_substream_count: 1
          expanded_loudspeaker_layout: EXPANDED_LOUDSPEAKER_LAYOUT_3_0_CH
        }
      ]
    }
  }
]

mix_presentation_metadata {
  mix_presentation_id: 42
  count_label: 1
  annotations_language: ["en-us"]
  localized_presentation_annotations: ["test_mix_pres"]
  num_sub_mixes: 1
  sub_mixes {
    num_audio_elements: 2
    audio_elements: [
      {
        audio_element_id: 300
        localized_element_annotations: ["test_sub_mix_0_audio_element_0"]
        rendering_config {
          headphones_rendering_mode: HEADPHONES_RENDERING_MODE_STEREO
        }
        element_mix_gain {
          param_definition {
            parameter_id: 999  # Non-existent; default will be used
            parameter_rate: 48000
            param_definition_mode: 1
            reserved: 0
          }
          default_mix_gain: -768
        }
      },
      {
        audio_element_id: 301
        localized_element_annotations: ["test_sub_mix_0_audio_element_1"]
        rendering_config {
          headphones_rendering_mode: HEADPHONES_RENDERING_MODE_STEREO
        }
        element_mix_gain {
          param_definition {
            parameter_id: 998  # Non-existent; default will be used
            parameter_rate: 48000
            param_definition_mode: 1
            reserved: 0
          }
          default_mix_gain: -768
        }
      }
    ]
    output_mix_gain {
      param_definition {
        parameter_id: 997  # Non-existent; default will be used
        parameter_rate: 48000
        param_definition_mode: 1
        reserved: 0
      }
      default_mix_gain: 0
    }
    num_layouts: 2
    layouts {
      loudness_layout {
        layout_type: LAYOUT_TYPE_LOUDSPEAKERS_SS_CONVENTION
        ss_layout {
          sound_system: SOUND_SYSTEM_A_0_2_0
          reserved: 0
        }
      }
      loudness {
        info_type_bit_masks: []
        integrated_loudness: -4122
        digital_peak: -815
      }
    }
    layouts {
      loudness_layout {
        layout_type: LAYOUT_TYPE_LOUDSPEAKERS_SS_CONVENTION
        ss_layout {
          sound_system: SOUND_SYSTEM_12_0_1_0
          reserved: 0
        }
      }
      loudness {
        info_type_bit_masks: []
        integrated_loudness: -5542
        digital_peak: -1646
      }
    }
  }
}

audio_frame_metadata: [
  {
    wav_filename: "sine_1000_4oa_48khz.wav"
    samples_to_trim_at_end: 640
    samples_to_trim_at_start: 0
    audio_element_id: 300
    channel_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
    channel_labels: ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15", "A16", "A17", "A18", "A19", "A20", "A21", "A22", "A23", "A24"]
  },
  {
    wav_filename: "Mechanism_5s.wav"
    samples_to_trim_at_end: 640
    samples_to_trim_at_start: 0
    audio_element_id: 301
    channel_ids: [0, 1, 2]
    channel_labels: ["L7", "R7", "C"]
  }
]

temporal_delimiter_metadata {
  enable_temporal_delimiters: false
}
